composer.json
Since the namespace was last changed, the `classmap` section of the Composer autoloader settings is not necessary.  This file is autoloaded anyway because of the `psr-4` section below.
=> Simplifying autoloader

src/Command/RequireCommand.php, src/Command/UpdateCommand.php
If the option doesn't exist in the definition, an error is thrown.
This makes flex compatible with Composer versions that do not have this option in the command definition.
Fixes #68
=> Make Flex compatible with Composer <1.3

src/ScriptExecutor.php
[ScriptExecutor] added check and use env COMPOSER_ORIGINAL_INIS variable.
After fresh install and `composer req cli` I got errors:
```
Executed script assets:install --symlink --relative web/  [KO]
[KO]
Script assets:install --symlink --relative web/ returned with error code 1
!!  Cannot load Zend OPcache - it was already loaded
!!  
!!  PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
!!  PHP Warning:  Module 'xml' already loaded in Unknown on line 0
!!  PHP Warning:  Module 'bcmath' already loaded in Unknown on line 0
!!  PHP Warning:  Module 'bz2' already loaded in Unknown on line 0
!!  PHP Warning:  Module 'calendar' already loaded in Unknown on line 0
!!  PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
!!  PHP Warning:  Module 'curl' already loaded in …
```
=> Check for COMPOSER_ORIGINAL_INIS env otherwise use regular php ini

src/Configurator/AbstractConfigurator.php
A newline is inserted after the data and before the end-section marker. Inserting empty lines in configuration files. 
Fixes #119
=> Right trimming configuration data before markers

src/Configurator/BundlesConfigurator.php, src/Configurator/ContainerConfigurator.php, src/Flex.php, tests/Configurator/BundlesConfiguratorTest.php, tests/Configurator/ContainerConfiguratorTest.php, tests/FlexTest.php
=> Move etc/ to config/ and web/ to public/

src/Configurator/AbstractConfigurator.php, src/Configurator/BundlesConfigurator.php, src/Configurator/ContainerConfigurator.php, src/Configurator/EnvConfigurator.php, src/Configurator/GitignoreConfigurator.php, src/Configurator/MakefileConfigurator.php, src/ScriptExecutor.php
Using `PHP_EOL` may cause issues when some developers use Windows while others use UNIX. I propose to follow the UNIX convention.
Still a WIP.
=> Use \n instead of PHP_EOL

src/Downloader.php, src/Flex.php, src/Recipe.php, tests/FlexTest.php
When using Flex "extensively", installing contrib repos is a bit frustrating. If you opt-out (the default), you have a warning that the recipe won't be installed. The way to fix it is to 1/ remove the package 2/ enable contrib 3/ reinstall the package.
Instead, what about asking the question to the user and act accordingly (that means less to learn as enabling contrib is done automatically when selecting `[p]`)?
=> Change the way we install contrib packages

src/Configurator/BundlesConfigurator.php, tests/Configurator/BundlesConfiguratorTest.php
Currently, when `config-dir` is changed in `composer.json`, the `bundles.php` file is the only one generated in a hard coded location (`config/bundles.php`). Everything else is nicely put in the directory configured in `composer.json`. 
This is an attempt to fix the issue so that `config-dir` is respected by flex consistently.
=> Do not rely on a hard coded config-dir in BundlesConfigurator

src/Configurator/BundlesConfigurator.php, tests/Configurator/BundlesConfiguratorTest.php
Before:
After:
In my opinion the second one looks better.
=> BundlesConfigurator: use ::class

.travis.yml, composer.json, src/Command/RemoveCommand.php, src/Command/RequireCommand.php, src/Command/UpdateCommand.php, src/Configurator.php, src/Configurator/AbstractConfigurator.php, src/Configurator/BundlesConfigurator.php, src/Configurator/ComposerScriptsConfigurator.php, src/Configurator/ContainerConfigurator.php, src/Configurator/CopyFromPackageConfigurator.php, src/Configurator/CopyFromRecipeConfigurator.php, src/Configurator/EnvConfigurator.php, src/Configurator/GitignoreConfigurator.php, src/Configurator/MakefileConfigurator.php, src/Downloader.php, src/Flex.php, src/Options.php, src/PackageResolver.php, src/Recipe.php, src/Response.php, src/ScriptExecutor.php
IMHO, enforcing 7.1 is only slowing down the adoption of Flex.
Unlike other existing projects that can tell "use the previous existing version",
we're starting with no community at all, and we want to spread adoption.
This is a strategic move to me.
Symfony 3.4 does work with 7.0, so PHP 7.0 users/companies that want to start new projects on it will have the choice to start with an already outdated standard edition, or nothing. This may hurt the Symfony project.
We have to provide a better alternative to them: Flex on PHP 7.0.
Here it is.
=> Make Flex work on PHP 7.0

src/Configurator/CopyFromPackageConfigurator.php, src/Configurator/CopyFromRecipeConfigurator.php
Negative string offsets (`$string[-1]`) only work since `7.1`:
* https://wiki.php.net/rfc/negative-string-offsets
* https://3v4l.org/kOlne
Other solution could be `substr($source, -1)` if your prefer.
=> Fix PHP 7.0 compatibility

src/Flex.php
This is a problem, as when you already have `extra.symfony.allow-contrib` set to either `true` or `"true"`, the question is still always asked, where it shouldn't.
=> Fix allow-contrib inconsistency before asking

src/Downloader.php, src/Flex.php, src/Lock.php, tests/FlexTest.php
To fix #192 and some more edge cases, we need a proper lock file for Symfony recipes instead of trying to guess via the state of Composer. The lock stores more than needed for now, but that opens up some more opportunities for the future.
fixes #192
=> Install fix with lock

src/Flex.php, tests/FlexTest.php
Should fix #198 - the `substr` logic was just reversed a bit.
=> Fixing a small bug in detecting PHP files

src/Configurator/EnvConfigurator.php, tests/Configurator/EnvConfiguratorTest.php
fixes symfony/recipes#233, #180, and #182
=> Fix escaping in .env and phpunit.xml.dist

src/ScriptExecutor.php
The arguments provided to the `StreamOutput` instance were not correctly set, leading to error messages with double line breaks like in this screenshot:
=> Fix line breaks for error messages

src/Configurator/ContainerConfigurator.php, src/Configurator/EnvConfigurator.php, src/SymfonyBundle.php, tests/Configurator/ContainerConfiguratorTest.php
Fixes #202
- Configure and add `parameters` key if it does not exists.
- Configure without duplicated.
- Complex configuration with linebreak and comments.
=> Fix container parameters configurator

src/Flex.php, tests/FlexTest.php
It's surprising to see "3.3" when installing a 4.0.0 component. This should fix it.
=> Add >= to "configuring" message

src/Flex.php, tests/FlexTest.php
Recipe for `symfony/framework-bundle` must be applied after recipe for `symfony/flex` and before all other recipes on install/update.
See #225
=> Sort recipes on update before configuration

src/Command/RequireCommand.php
My solution to fix #252 .
As said in the title I'd say it's only needed to unpack the packages if the user entered a package. With this fix you can just use "composer require" again and search for packages using the composer suggestions.
=> Only try to unpack packages when the user used a package name

src/Flex.php, src/ParallelDownloader.php
Purpose
-------
This PR is heavily inspired by the great [hirak/prestissimo](https://github.com/hirak/prestissimo) by Hiraku NAKANO.
Its purpose is to provide a portable alternative to `hirak/prestissimo`, so that it can be bundled by default into Flex: unlike `hirak/prestissimo`, it doesn't require the `curl` extension and has zero extra dependencies. Instead, it reuses the existing code infrastructure in Composer to download packages.
If `hirak/prestissimo` is installed, this behavior disables itself automatically.
Limitations
-----------
- By reusing Composer's downloader, it is not possible to create server connections concurrently.
Instead, the second download is started when the first one receives its first bytes from the server, and so on.
- JSON files downloaded from package …
=> Speedup Composer by downloading packages in parallel

src/Flex.php
Sending certain unicode values to STDOUT may cause Docker terminals to abruptly quit and disconnect for some users, as noted in docker/toolbox#695  and moby/moby#22345. In this particular case the issue is triggered by the emoji star (U+2B50) which was added in #262 / 0a45ec98fe91340001746baa1336c5d9d827f938 . 
While this is **not a bug in Flex**, I still recommend skipping the cosmetic emojis, since their appeal is probably outweighed by the impact and users and the potential that some users will incorrectly blame Flex when `composer update` disconnects their terminal halfway through the "thanks reminder."
=> Workaround: Avoid emojis which cause terminal failures in Docker

src/ComposerRepository.php, src/CurlDownloader.php, src/Downloader.php, src/Flex.php, src/ParallelDownloader.php
This PR brings hirak/prestissimo-like download performance to Flex, but with greater compatibility with Composer's native behavior, thanks to a new extension point that is going to be part of Composer 1.7 (https://github.com/composer/composer/pull/6985).
Meanwhile, it already provides concurrent connections, and auto-enables the curl-based downloader conditionally.
In short, it should be totally seamless.
=> Leverage ext-curl when possible to achieve high speed downloads

tests/FlexTest.php
Tests were failing on Windows.
```
λ vendor\bin\simple-phpunit.bat
PHPUnit 5.7.26 by Sebastian Bergmann and contributors.
Testing Symfony Flex Test Suite
..........F...................                                    30 / 30 (100%)
Time: 428 ms, Memory: 6.00MB
There was 1 failure:
1) Symfony\Flex\Tests\FlexTest::testPostInstall
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
#Warning: Strings contain different line endings!
Symfony operations: 1 recipe ()
- Configuring dummy/dummy (>=1.0): From github.com/symfony/recipes:master
```
```
λ vendor\bin\simple-phpunit.bat
PHPUnit 5.7.26 by Sebastian Bergmann and contributors.
Testing Symfony Flex Test Suite
..............................                                    30 / 30 (100%)
Time: 752 ms, Memory: …
```
=> Fix tests on Windows: Normalize line-endings

src/Flex.php
Right now, the reminder is displayed when running composer update with no composer.lock file.
This was not intended. Here is what was to me :)
Sibling to https://github.com/symfony/thanks/pull/38
=> Display thanks reminder only when a package is actually updated

src/CurlDownloader.php
This option was added in libcurl 7.30 which is not available by default on RHEL distros. 
Added a check before setting this option.
=> Check max host connections option is available

src/Configurator/MakefileConfigurator.php
does not use grep anymore, awk can do this as well
=> simplify matching for showing makefile targets

src/Flex.php, tests/FlexTest.php
When Composer is run with `no-dev`, Flex must ignore any dev package uninstallations. fixes #268
=> Fix composer --no-dev mode

src/Configurator/CopyFromPackageConfigurator.php
bug symfony/flex#325 CopyFromPackage unconfigure is not removing files when using special directories like %PUBLIC_DIR%
=> bug symfony/flex#325 CopyFromPackage unconfigure is not removing files

tests/Configurator/CopyDirectoryFromPackageConfiguratorTest.php
This PR
Follows https://github.com/symfony/flex/pull/356/files#r184845342.
=> Fix: Use strict comparison

tests/Configurator/BundlesConfiguratorTest.php, tests/Configurator/ContainerConfiguratorTest.php, tests/Configurator/EnvConfiguratorTest.php, tests/Configurator/GitignoreConfiguratorTest.php, tests/Configurator/MakefileConfiguratorTest.php
=> Fix: Use class keyword instead of string literals

.gitignore, .php_cs.dist, src/Command/FixRecipesCommand.php
This PR
Spotted in #365.
Follows #364.
💁‍♂️ Running
```
$ php-cs-fixer fix
```
yields
```
Loaded config default from "/Users/am/Sites/symfony/flex/.php_cs.dist".
In Finder.php line 568:
You must call one of in() or append() methods before iterating over a Finder.
fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
```
which reflects the complaints by fabbot.io in #365:
=> Fix: Sort out configuration for friendsofphp/php-cs-fixer

.travis.yml, composer.json
This PR
💁‍♂️ Running
``` 
$ composer validate
```
yields
```
/composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
description : The property description is required
```
=> Fix: Provide missing description

src/Cache.php, src/ComposerRepository.php, src/Flex.php, tests/FlexTest.php
Before:
> Memory usage: 272.59MB (peak: 606.6MB), time: 5.79s
After:
> Memory usage: 145.56MB (peak: 158.56MB), time: 1.86s
=> Removing legacy tags significantly reduces memory and CPU usage

README.md, src/Downloader.php, src/Response.php
Several companies reported that they have problems with symfony.sh (blocked by their proxies). I got one more report today, so let's move away from this specific domain and move to `https://flex.symfony.com` as the default endpoint (I didn't want to do that at first because I didn't want to expose `flex` anywhere, but I suppose that purely internal and I can live with that).
=> Move away from symfony.sh

src/Cache.php
Not all files loaded from cache are provider-style files. Private Packagist for example serves all packages in one request for efficiency and the current flex code was then happily removing any package's version below 3.4.0 when doing so.
=> Avoid removing versions of unrelated packages when loading non-provider files

src/ParallelDownloader.php, src/Unpacker.php, tests/Configurator/ContainerConfiguratorTest.php, tests/Configurator/EnvConfiguratorTest.php, tests/Configurator/GitignoreConfiguratorTest.php, tests/Configurator/MakefileConfiguratorTest.php, tests/FlexTest.php
Required after https://github.com/composer/composer/pull/7495
Code is compatible with both signatures.
=> Add compatibility with updated RemoteFilesystem::getRemoteContents() signature

src/PackageResolver.php
Fixes #394
The recipe validation server should also have a rule to fail when an alias on "mirrors" or "nothing" is submitted.
Composer also handles "lock" as a special alias, but we already have the lock component, let's take priority.
=> Handle composer special aliases "mirrors" and "nothing"

.travis.yml, src/Cache.php, src/Downloader.php, src/Flex.php, src/Lock.php, src/ParallelDownloader.php, src/Recipe.php, src/TruncatedComposerRepository.php, tests/FlexTest.php
The C.I. for `symfony/symfony` is starting to fail transiently because solving the dependency graph takes too much memory.
See e.g. https://ci.appveyor.com/project/fabpot/symfony/build/1.0.39377
But thanks to recent improvements in Flex, we know why and how to fix that: skipping old tags.
This PR allows using Flex while disabling the recipes subsystem and allows configuring the minimum version of components we give to the solver.
I plan to use the next version of Flex that embeds this PR (could be v1.1.0 btw) on `symfony/symfony`.
=> Add SYMFONY_REQUIRE env var + disable recipes when flex is not in the root composer.json

src/Downloader.php, src/Flex.php
=> Reenable flex when it is found in require-dev

phpunit.xml.dist, src/Cache.php, tests/CacheTest.php
Fixes #410
ping @pamil, please confirm.
=> Don't filter packages that have empty intersection with symfony/symfony when matching extra.symfony.require

src/Flex.php, src/PackageResolver.php
Fixes https://github.com/symfony/flex/issues/433
Fixes https://github.com/symfony/flex/issues/421
When a new project is created, this makes flex replace `"*"` constraints by the one specified in `extra.symfony.require`.
The same logic also applies to `composer require symfony/*`
=> Bound constraints by copying extra.symfony.require

src/Flex.php
Fixes https://github.com/symfony/flex/issues/436
=> Ignore "extra.symfony.require" when running the "outdated" command

src/PackageResolver.php
When trying to install a symfony/* package without the `extra.symfony.require` composer option we run into an undefined index error.
Seems to be caused by db60ae8
=> Fix undefined index in package resolver

src/Flex.php
=> Avoid remove author name

.gitignore, composer.json, phpunit.xml.dist, src/Command/SyncRecipesCommand.php, src/Configurator.php, src/Configurator/AbstractConfigurator.php, src/Configurator/BundlesConfigurator.php, src/Configurator/ComposerScriptsConfigurator.php, src/Configurator/ContainerConfigurator.php, src/Configurator/CopyFromPackageConfigurator.php, src/Configurator/CopyFromRecipeConfigurator.php, src/Configurator/EnvConfigurator.php, src/Configurator/GitignoreConfigurator.php, src/Configurator/MakefileConfigurator.php, src/Event/UpdateEvent.php, src/Flex.php, src/Options.php, tests/Configurator/BundlesConfiguratorTest.php, tests/Configurator/ContainerConfiguratorTest.php, tests/Configurator/CopyDirectoryFromPackageConfiguratorTest.php, tests/Configurator/CopyFromPackageConfiguratorTest.php, tests/Configurator/CopyFromRecipeConfiguratorTest.php, tests/Configurator/EnvConfiguratorTest.php, tests/Configurator/GitignoreConfiguratorTest.php, tests/Configurator/MakefileConfiguratorTest.php, tests/Configurator/TmpDirMock.php, tests/FlexTest.php, tests/bootstrap.php
=> Implement "sync-recipes --force" option

src/Configurator/AbstractConfigurator.php, src/Configurator/BundlesConfigurator.php, src/Configurator/ContainerConfigurator.php, src/Configurator/CopyFromPackageConfigurator.php, src/Configurator/CopyFromRecipeConfigurator.php, src/Configurator/EnvConfigurator.php, src/Configurator/GitignoreConfigurator.php, src/Configurator/MakefileConfigurator.php, src/Flex.php, src/ScriptExecutor.php, tests/Configurator/BundlesConfiguratorTest.php, tests/Configurator/ContainerConfiguratorTest.php, tests/Configurator/CopyDirectoryFromPackageConfiguratorTest.php, tests/Configurator/CopyFromPackageConfiguratorTest.php, tests/Configurator/CopyFromRecipeConfiguratorTest.php, tests/Configurator/EnvConfiguratorTest.php, tests/Configurator/GitignoreConfiguratorTest.php, tests/Configurator/MakefileConfiguratorTest.php, tests/bootstrap.php
Fixes https://github.com/symfony/flex/issues/243
and makes path management a bit more flexible.
=>  Allow configuring the "extra.symfony.root-dir" of the Symfony app 

src/Flex.php, src/Lock.php
Fixes #461 in a pragmatic way, without any of the complexity that is described in the issue :)
Should cover 80% of the need for 5% of the effort.
=> Skip up-to-date recipes when using sync-recipes --force

src/Flex.php
When uninstalling a package with a found recipe, Flex unconfigures it even if it was not configured before.
=> Do nothing when uninstalling unconfigured packages

src/Flex.php
Allows to ignore incompatible recipes, helpful to avoid breaking apps using FrameworkBundle LTS versions.
Unlocks https://github.com/symfony/recipes/pull/506.
We need to update the Symfony bot to allow the `conflict` key in the `manifest.json`, ping @fabpot :).
=> Added support for recipes conflict

src/Configurator/AbstractConfigurator.php
For more information, see issue [#523](https://github.com/symfony/recipes/issues/523) from the symfony/recipes repo.
=> Fix file_get_content exception when installing symfony 4.3-dev

src/Configurator.php, src/Configurator/AbstractConfigurator.php, src/Configurator/BundlesConfigurator.php, src/Configurator/ComposerScriptsConfigurator.php, src/Configurator/ContainerConfigurator.php, src/Configurator/CopyFromPackageConfigurator.php, src/Configurator/CopyFromRecipeConfigurator.php, src/Configurator/EnvConfigurator.php, src/Configurator/GitignoreConfigurator.php, src/Configurator/MakefileConfigurator.php, src/Flex.php, src/Lock.php, src/Options.php, tests/Configurator/BundlesConfiguratorTest.php, tests/Configurator/ContainerConfiguratorTest.php, tests/Configurator/CopyDirectoryFromPackageConfiguratorTest.php, tests/Configurator/CopyFromPackageConfiguratorTest.php, tests/Configurator/CopyFromRecipeConfiguratorTest.php, tests/Configurator/EnvConfiguratorTest.php, tests/Configurator/GitignoreConfiguratorTest.php, tests/Configurator/MakefileConfiguratorTest.php
This PR modifies the `CopyFromRecipeConfigurator` so that it will store a list of copied files in symfony.lock and when a recipe is about to be unconfigured, it will check the list of locked files to prevent removal. This should fix #428 
```
composer create-project symfony/skeleton example
cd example
composer remove console
```
This will remove both files installed through the recipe `bin/console` and `config/bootstrap.php`. As `symfony/framework-bundle` relies on the bootstrap-file as well, when trying to access the website, you will get an error due to the missing file.
Create a new project based on `symfony/skeleton` and replace flex inside the example project with a local copy of this branch:
```
composer create-project symfony/skeleton example
cd example
rm -rf vendor/symfony/flex …
```
=> Lock copied files to prevent removing files needed by other recipes

src/Lock.php
Fixed #379 by only writing the Lockfile when something has changed (which is not the case on `composer install`).
This seems to me the best solution for the linked issue:
* no change in the Flex behaviour on `composer install` needed (still doing the same like on `composer update`)
* only update the Lockfile when needed (even the modification timestamp will stay the same)
* working for all composer actions (because of auto detection)
Thank you for your feedback.
=> only write lock when its content has changed

src/Command/DumpEnvCommand.php
Fix #475
Fix #476
Fix https://github.com/symfony/symfony/pull/30418
=> Ignore existing env vars when running dump-env

src/Configurator/BundlesConfigurator.php, tests/Configurator/BundlesConfiguratorTest.php
Fix when we set an environment to `false` in bundle.php it set at `true` on generation.
=> Fix bundles.php generation when false value is used

src/CurlDownloader.php
Fix #488.
I'm working behind a corporate proxy and since few days, I get errors like in the screenshot below whenever I use flex.
Further debugging revealed that [composer replace the http scheme by tcp in the proxy url](https://github.com/composer/composer/blob/1.8.5/src/Composer/Util/StreamContextFactory.php#L78), which curl doesn't support.
As curl reads proxy conf from env by default, let's just not override it.
=> Fix proxy handling

src/Configurator/ContainerConfigurator.php, tests/Configurator/ContainerConfiguratorTest.php
Escapes the regex of the container configurator because for the case of the variables "env()" this one are broken.
Example with the mercure or doctrine/mongodb-odm-bundle recipe if you remove the dependence.
=> Improve regex for container configurator

src/Command/DumpEnvCommand.php
Sometimes the useful info is on stdout.
=> Display stdout too when dump-env fails

src/Cache.php
Fixes #508
Happens on the CI when local packages are built for testing PRs.
=> Fix dealing with locally patched packages

src/CurlDownloader.php
cref https://github.com/symfony/flex/issues/515
@ https://curl.haxx.se/libcurl/c/CURLMOPT_PIPELINING.html
```
HTTP/1 Pipelining support was disabled in 7.62.0. 
```
here
```
lsb_release -rd
Description:    openSUSE Leap 15.1
Release:        15.1
curl -V
curl 7.65.1 (x86_64-suse-linux-gnu) libcurl/7.65.1 OpenSSL/1.1.0i-fips zlib/1.2.11 libidn2/2.2.0 
...
```
manually
```
src/CurlDownloader.php
-	        curl_multi_setopt($mh, CURLMOPT_PIPELINING, /*CURLPIPE_HTTP1 | CURLPIPE_MULTIPLEX*/ 3);
+	        curl_multi_setopt($mh, CURLMOPT_PIPELINING, /*CURLPIPE_MULTIPLEX*/ 2);
```
now, check
```
composer --version
Composer version 1.8.6 2019-06-11 15:03:05
```
=> remove deprecated CURLPIPE_HTTP1 support flag

composer.json, src/Cache.php, src/Downloader.php, src/Flex.php, src/PackageResolver.php, src/ParallelDownloader.php, tests/PackageResolverTest.php
The goal of this PR is to remove the need for any skeleton-bot as used in https://github.com/symfony/skeleton/pulls?q=is%3Apr+is%3Aclosed+author%3Asymfony-skeleton-bot
As a reminder, this bot is currently needed to generate a `composer.lock`. And this file is needed because it's part of a work around to fix a combinatorial explosion when Composer solves dependencies.
This PR makes `create-project` a two steps process: first, a skeleton is installed with only flex in "require". When flex is installed and composer enables it, the plugin looks for specific entries in the composer.json file, namely "flex-require" and "flex-require-dev". It merges them with regular "require" and "require-dev", and runs a new "composer update" internally.
This also fixes the combinatorial explosion and allows …
=> Merge new "flex-require" section with "require" on create-project & update

src/Configurator.php, src/Configurator/DockerComposeConfigurator.php, src/Configurator/DockerfileConfigurator.php, tests/Configurator/DockerComposeConfiguratorTest.php, tests/Configurator/DockerfileConfiguratorTest.php
/!\ This piece of software is experimental and may break your app. Don't use it without a proper versioning strategy.
This is a part of my global plan to add a first-class Docker support in Symfony. It requires https://github.com/dunglas/symfony-docker-skeleton/pull/5.
This PR allows recipes to updates `docker-compose.yaml` (to add services and volumes for instance) and the `Dockerfile` (to add PHP extensions for instance).
I'll blog about this when I'll be back from vacation.
=> Docker support (Docker Compose and Dockerfile)

src/ParallelDownloader.php
This should fix #528.
Before:
```
root@bafcbe268c5d:/projects/test# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 27 installs, 0 updates, 0 removals
- Installing symfony/flex (dev-fix/disable-emojis-by-is-decorated 7e14191): Downloading (100%)
Prefetching 26 packages 🎶 💨
- Downloading (100%)
- Installing psr/cache (1.0.1): Loading from cache
- Installing symfony/cache-contracts (v1.1.5): Loading from cache
- Installing psr/container (1.0.0): Loading from cache
- Installing symfony/service-contracts (v1.1.5): Loading from cache
- Installing symfony/polyfill-php73 (v1.11.0): Loading from cache
- …
```
=> Don't output emojis when the output isn't being decorated

src/Flex.php
`require_once` doesn't work when flex is loaded from two separate directories (global + local)
=> Fix "Cannot declare class because the name is already in use" errors

src/Configurator/DockerComposeConfigurator.php, tests/Configurator/DockerComposeConfiguratorTest.php, tests/Configurator/DockerfileConfiguratorTest.php
When you delete a recipe from the volumes section when there are only recipes, the "volumes" keywords are deleted.
cc @dunglas
=> Fix docker configurator with many mark in volumes section

src/ParallelDownloader.php
Fixes #560 
Currently Flex breaks installations of local packages via the composer built-in repository types:
- artifact repository (see #560)
- package repository (see #548)
This PR leaves the download to the original composer downloader, in case the URL of the package does not start with `http(s):`.
I found a very similar code piece in https://github.com/symfony/flex/blob/master/src/Flex.php#L605 (just for reference for maintainer).
=> Skip parallel downloader for local files

src/ParallelDownloader.php
On a big work project I noticed that with an empty composer cache the pre-fetching of packages has become really slow lately.
Here a comparison between flex and `hirak/prestissimo`:
flex:
https://blackfire.io/profiles/eb7cfd59-6d88-4035-b210-661a5f0de666/graph
prestissimo:
https://blackfire.io/profiles/07b46d2e-3912-41c5-b25c-5b39a3103de9/graph
In my case curl was not used at all :stuck_out_tongue: 
This PR aims to fix the wrong bypass condition that was added within https://github.com/symfony/flex/pull/561.
Thanks @nicolas-grekas for the help.
=> fix wrong bypass of parallel downloads

composer.json
Fixes #569
When using plugins, the composer autoloader use local project dependencies that match the plugin's `require`+`require-dev` dependencies.
Given flex plugin requires-dev `symfony/dotenv: ^3.4|^4.0`, composer's autoloader was not able to load the class Dotenv when in a project that requires `symfony/dotenv: ^5.0`.
=> Fix Symfony 5 - dump-env

src/Flex.php
When e.g. PHP 7.3 is used to compute dependencies, here is the message that is now generated when running `bin/console` or `symfony serve` *on PHP 7.1*:
```
Fatal Error: composer.lock was created for PHP version 7.3 or higher but the current PHP version is 7.1.33.
```
We have too many reports on symfony/symfony about ppl that mess up with these.
It works by adding a simple *static* check in `vendor/autoload.php`.
Note that `composer install` already yells, so it's already covered.
=> Enforce PHP version at runtime to be same or higher as at "composer update" time

src/Cache.php
A constraint like `">5.0.0,<5.1"` in `SYMFONY_REQUIRE` doesn't work right now, this fixes it.
=> Fix computing the intersection of Symfony components with extra.symfony.require

src/Lock.php
In https://github.com/symfony/flex/pull/479 I tried to fix the issue https://github.com/symfony/flex/issues/379 by introducing a _changed_ flag to the Lock.
This patch worked for a few months. However, introducing https://github.com/symfony/flex/pull/576 broke the patch by [always calling](https://github.com/symfony/flex/pull/576/files#diff-46b78198ae7ea525f04268205dd782c3R273) `set` ending in the same situation as before.
Blame on me for not checking if anything differs before setting the _changed_ flag. This PR tries to do better.
=> compare data before marking lock as changed

src/Command/RecipesCommand.php, src/Flex.php
Hi!
This replaces #585 and builds off of #562. 
Basically, I *thought* that it would be nearly impossible to get the *exact* git sha for when a recipe is installed. But with a few API calls to GitHub, it's quite possible :). This gives us the ability to (at least) give the URL to the *exact* state of the recipe when it was installed in their app. This can help them determine what's changed and if they need to update.
Giving them a "diff" URL would be even more awesome - but as the directory often changes - I don't believe there is any URL we can give to visually compare across directories. Output:
The "installed recipe" is the line that this enables. The "new commits" line (unfortunately) can only be shown when the version/directory of the recipe hasn't changed. There's just not good way …
=> Adding the current recipe URL to recipes <recipe> output

src/Flex.php, tests/FlexTest.php, tests/SymfonyBundleTest.php
Bundles autodiscovery is now enabled for all the packages, but not only for `symfony-bundle` type packages. And it works in the same way as it worked before. 
PR description before @fabpot review:
> 1. Bundles autodiscovery is now enabled for all the packages, but not only for `symfony-bundle` type packages. And it works in the same way as it worked before. It is disabled only when there is `extra.symfony.bundles` configuration in the package (even if this configuration is an empty array).
> 2. New `extra.symfony.bundles` package configuration was introduced. It should contain the list of bundles and the environments where those bundles should be enabled. Example:
>     ```
>     "extra": {
>         "symfony": {
>             "bundles": {
>                 "VendorName\\BundleName1": …
```
=> Enable bundles auto-discovery by default

src/SymfonyBundle.php, tests/Fixtures/vendor/composer/ca-bundle/src/CaBundle.php, tests/Fixtures/vendor/doctrine/doctrine-cache-bundle/DoctrineCacheBundle.php, tests/Fixtures/vendor/dunglas/sylius-acme-plugin/src/DunglasSyliusAcmePlugin.php, tests/Fixtures/vendor/easycorp/easy-deploy-bundle/src/EasyDeployBundle.php, tests/Fixtures/vendor/easycorp/easy-security-bundle/EasySecurityBundle.php, tests/Fixtures/vendor/eightpoints/guzzle-bundle/EightPoints/Bundle/GuzzleBundle/GuzzleBundle.php, tests/Fixtures/vendor/sylius/shop-api-plugin/src/ShopApiPlugin.php, tests/Fixtures/vendor/symfony-cmf/routing-bundle/CmfRoutingBundle.php, tests/Fixtures/vendor/symfony/debug-bundle/DebugBundle.php, tests/Fixtures/vendor/symfony/dummy/FirstDummyBundle/FirstDummyBundle.php, tests/Fixtures/vendor/symfony/dummy/SecondDummyBundle/SecondDummyBundle.php, tests/Fixtures/vendor/symfony/nouse-bundle/NouseBundle.php, tests/Fixtures/vendor/web-token/jwt-bundle/JoseFrameworkBundle.php, tests/FlexTest.php
=> Fix bundle auto-detection

.gitignore, .php_cs.dist, src/CurlDownloader.php
Fixes #468 
This change skips tracking the progress of downloads where `Content-Length` header is missing. Curl returns `-1` which resulted in wrong progress calculation (total file size was not added to the total bytes to download).
As soon as such file is downloaded, the progress is updated. This means that downloading one big file might cause progress to stuck until the download is done.
=> avoid >100% progress

src/Command/RequireCommand.php, src/Flex.php
Removes `You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.`
=> Remove notice about deprecated --no-suggest when using Composer v2

src/Command/UnpackCommand.php, src/Flex.php, src/Unpacker.php
This PR ensures that packs are auto-unpacked when they are found in the `flex-require` or `flex-require-dev` sections, which happens when running e.g. `composer create-project symfony/(website-)skeleton`.
On the path to #645
=> Auto-unpack on create-project

src/Command/RequireCommand.php
Packs are like meta-recipes: ppl should adopt them in their root composer.json so that updating packs (like updating recipes) doesn't affect their project.
If one needs to delegate the selection of a group of packages, they should use the `meta-package` type of composer instead.
Fixes #645
=> Unpack by default when running composer require

src/Configurator/CopyFromRecipeConfigurator.php, tests/Configurator/CopyFromRecipeConfiguratorTest.php
Use `realpath` to compare locked files before removal.
Fixes #513
To test:
```
composer create-project symfony/skeleton example
cd example/vendor/symfony/
rm -rf flex
git clone https://github.com/leongersen/flex --branch issue-513 --single-branch
cd ../../
composer require symfony/test-pack
composer remove symfony/test-pack
```
=> Compare paths by their realpath when checking locks

src/Flex.php, tests/FlexTest.php
Discovering the `composer recipes` command during composer install/update
Fix issue #629 and move forward #518 - 8)
=> Improve discoverability of 'composer recipes'

src/PackageFilter.php
It'd be good to add tests for this ... and I am not sure if the branch-alias check at line 67/68 is still needed if aliases are handled properly, might be or might not be.. I don't fully grasp the scope of what flex does here.
=> Avoid filtering out aliases of valid packages

src/Configurator/DockerComposeConfigurator.php, tests/Configurator/DockerComposeConfiguratorTest.php
Allows recipes to ship configuration for multiple Docker Compose files (e.g. `docker-compose.override.yml`, `docker-compose.production.yml`). This is convenient to provide different settings for the development and the production environment. This is a companion PR for dunglas/symfony-docker#73.
=> Add support for multiple Docker Compose files

src/Command/InstallRecipesCommand.php
As spotted in https://github.com/symfony/flex/pull/684#issuecomment-708228981
=> Fix description of flag "--force" of the recipes:install command

src/Configurator/EnvConfigurator.php
This is the case if someone wants to add a blank line.
```diff
-# 
+#
```
=> Fix: Remove trailing whitespace if value is empty

src/Flex.php
Incredibly pedantic (sorry!) but I noticed this when updating Symfony Flex.
=> Fixed capitalisation of JavaScript

src/PackageResolver.php, tests/PackageResolverTest.php
**Context**
I discovered this issue from a personal specific script, when a bash variable was not set properly.
I get this PHP error from flex:
```
[ErrorException]        
strpos(): Empty needle
```
**How to reproduce**
```
symfony new test --version=lts
cd test
composer require symfony/yaml:$VERSION
```
=> [COMPOSER] Fix strpos(): Empty needle when using bash variables

src/PackageJsonSynchronizer.php, tests/Fixtures/packageJson/vendor/symfony/existing-package/Resources/assets/package.json, tests/Fixtures/packageJson/vendor/symfony/new-package/assets/package.json, tests/PackageJsonSynchronizerTest.php
Partner to https://github.com/symfony/stimulus-bridge/pull/15 and https://github.com/symfony/ux/pull/53
The tricky part about this is that, if the user has `stimulus-bridge` 1.x, then their `controllers.json` file needs `webpackMode`. If they have `stimulus-bridge` "next" (we're thinking it'll be 2.0), then their `controllers.json` file needs `fetch`. This means that Flex has a "hard break" and sorta just needs to assume that the user has the "new" version.
We made the decision - to go from `webpackMode` to `fetch` because the setting no longer is truly the same as `webpackMode`. However, if we wanted to make the upgrade path easier, we could revert that and use `webpackMode` in 2.0 as well (instead of changing to `fetch`).
=> Changing to support next version of stimulus bridge with "fetch" mode

src/Flex.php
Removing the command constructor inherited the parent one passing a name as first argument.
Closes #759
=> Fix the deprecation of the id generation command

src/Command/GenerateIdCommand.php, src/Downloader.php, src/Flex.php
Composer fails during the upgrade of symfony/flex
```
$ composer create-project symfony/skeleton flex && cd flex
$ composer require symfony/flex dev-main -v
./composer.json has been updated
Running composer update symfony/flex
> pre-update-cmd: Symfony\Flex\Flex_composer_tmp0->configureInstaller
Loading composer repositories with package information
> pre-pool-create: Symfony\Flex\Flex_composer_tmp0->truncatePackages
Updating dependencies
Dependency resolution completed in 0.000 seconds
Analyzed 135 packages to resolve dependencies
Analyzed 210 rules to resolve dependencies
Lock file operations: 0 installs, 1 update, 0 removals
Updates: symfony/flex:dev-main 4d7970f
- Upgrading symfony/flex (v1.12.2 => dev-main 4d7970f)
Writing lock file
Installing dependencies from lock file (including …
```
=> Fix errors during the upgrade or downgrade of symfony/flex

src/Event/UpdateEvent.php, src/Flex.php
composer install should be read-only, so this doesn't make much sense and this spams the console with unneeded messages.
=> Don't try to update package.json on composer install

src/PackageJsonSynchronizer.php, tests/Fixtures/packageJson/package.json, tests/PackageJsonSynchronizerTest.php
Currently, each time `composer install` is run, it changes the formatting of arrays keys in `package.json`:
```diff
{
-   "browserslist": [
-      "defaults"
-   ]
+   "browserslist": ["defaults"]
}
```
This is especially annoying since `npm install` actually reverts it to the previous formatting, so it's a constant "battle" between the two package managers.
=> Package JSON sync alters array formatting

src/Configurator/CopyFromPackageConfigurator.php, tests/Configurator/CopyDirectoryFromPackageConfiguratorTest.php
Potential fix for https://github.com/symfony/flex/issues/755
I've:
1) added a test that uncovers the issue - even when `force` is used the existing files are not overwritten
2) added a test that makes sure the behaviour does not change when force is not used
3) fixed the issue by respecting the `force` option in `copyDir` method.
=> Fix copy from package with directories

src/Command/DumpEnvCommand.php, tests/Command/DumpEnvCommandTest.php
`--env` would be an option, but `env` is an argument.
And the suggested/hinted
```bash
composer dump-env --env=prod
```
doesn't work
=> Clarify the dump-env exception message

src/PackageJsonSynchronizer.php, tests/Fixtures/packageJson/vendor/symfony/existing-package/composer.json, tests/Fixtures/packageJson/vendor/symfony/new-package/composer.json
=> Require UX packages to have the "symfony-ux" keyword in their composer.json file

src/Downloader.php
Writing to the cache with an empty key will fail with "failed to open stream: Is a directory", so do not try to do that.
We noticed this when cloudflare - or the backend service - responded with a "last-modified" header for our CI servers (AWS) but not for our local system. This triggered the condition to become true and it tries to write a cache file without a filename.
I hope this is the correct place to fix it, but from what I see, this code should not try to write a cache with am empty key, correct?
Here is how a `composer install` failed for us (because of this?): 
```
[ErrorException]                                                                                              
file_put_contents(/tmp/composer/cache/repo/https---flex.symfony.com/): failed to open stream: Is a …
```
=> do not try to write a cache entry if there is no cache key

src/Command/RequireCommand.php, src/Command/UnpackCommand.php
Fixes a minor glitch where "require-dev" currently ends last in `composer.json` after a `composer req`.
This fixes it by keeping the empty entry if it's there before the run.
=> Preserve position of require-dev when it's empty before running "require"

src/Configurator/DockerComposeConfigurator.php, tests/Configurator/DockerComposeConfiguratorTest.php
If you want to use Docker support in Flex, you must configure it explicitly in a project (via `symfony composer config extra.symfony.docker true` for instance). But that's not enough. You must also create the `docker-compose.yaml` file. And if you do not also create the `docker-compose.override.yaml` file, you will end up with half of the configuration.
In this PR, I propose to create those 2 files automatically if they don't exist when a service should be added by a recipe.
That way, using Docker support is "only" a matter of opting-in via `composer.json`.
/cc @dunglas
=> Automatically create Docker Compose files when needed

src/Flex.php
When installing a pack, the `executeAutoScripts()` is not ran, so we need to explicitly display the post install output in `reinstall()` as well.
=> Fix post install output not displayed when installing a pack

src/PackageResolver.php
`composer update symfony/* bar*  -v` yields:
```
[UnexpectedValueException]
Could not parse version constraint "bar*".
Exception trace:
() at ./vendor/symfony/flex/src/PackageResolver.php:144
Symfony\Flex\PackageResolver->throwAlternatives() at ./vendor/symfony/flex/src/PackageResolver.php:64
Symfony\Flex\PackageResolver->resolve() at ./vendor/symfony/flex/src/Flex.php:245
Symfony\Flex\Flex->activate() at /var/www/composer/src/Composer/Plugin/PluginManager.php:334
Composer\Plugin\PluginManager->addPlugin() at /var/www/composer/src/Composer/Plugin/PluginManager.php:229
```
While really within the update context, these are just package names, or pkg version pairs but then with a separator, 
Valid for `update` are `pkg/name`, `pkg*` (wildcard anywhere), `pkg/name:constraint`, …
=> Fix handling of wildcards without slash in update command

src/Flex.php
Fixes #796 
We don't need to use `\DIRECTORY_SEPARATOR` here, as [**symfony/filesystem**](https://github.com/symfony/filesystem/blob/4.4/Filesystem.php#L451) already normalizes windows directory separator to use forward slash.
=> Fixed directory separator trimming in vendors path

src/PackageJsonSynchronizer.php
=> Keep package.json entries that dont match the ones managed by flex

src/Command/RecipesCommand.php
This fixes a little edge-case while testing out the new flex endpoint feature.
How to reproduce the bug:
1. You don't use `flex://default` (so only allow internally maintained recipes)
2. You previously used Symfony's recipes to set-up the project
3. Now, the locked recipe ref for e.g. FrameworkBundle no longer matches the ref from the auto-generated recipe for bundles
4. This means you'll get "(update available)" when running `composer recipes`
If you install a new bundle, there is no locked ref and you'll get the "(recipe not installed)" message for auto-generated recipes, as expected.
=> Do not mark auto recipes as "update as available" (if private repository doesn't contain the recipe)
