src/Flex.php
tests/FlexTest.php

Fixes https://github.com/symfony/recipes/issues/12

Expand special %DIR% variables in post-install-output

---

src/Configurator/BundlesConfigurator.php
src/Configurator/EnvConfigurator.php
src/Configurator/GitignoreConfigurator.php
src/Configurator/MakefileConfigurator.php
src/Downloader.php
src/Flex.php
src/PackageResolver.php
src/Recipe.php
src/Response.php
src/ScriptExecutor.php

Mostly phpdoc for IDEs when needed (self-documented parameters are not useful to document, unless there's documentation about exceptions, this is why sometimes there is phpdoc and sometimes not).
Also, there was some unused classes and some missing strict checks .

Some CS fixes

---

src/Configurator/BundlesConfigurator.php

clean opcode caches after writing the bundles file

---

src/Downloader.php
src/Flex.php
src/Recipe.php
src/Response.php
tests/FlexTest.php

Add the recipe origin in the Composer output

---

src/Downloader.php
src/Flex.php
src/Recipe.php
tests/FlexTest.php

Optimize performance by getting all recipes in one HTTP request

---

src/Flex.php
tests/FlexTest.php

Fix not configuring recipes on composer install and fixed duplicate installs

---

src/ScriptExecutor.php

Fix for requested change in #116 , in console output it now shows the folder instead of %WEB_DIR% etc.

Display folder name in console output instead of variable.

---

src/SymfonyBundle.php
tests/SymfonyBundleTest.php

Add support for more bundle class names

---

src/Configurator/GitignoreConfigurator.php
src/Configurator/MakefileConfigurator.php
tests/Configurator/GitignoreConfiguratorTest.php
tests/Configurator/MakefileConfiguratorTest.php

Fix edge case on .gitignore management

---

src/Flex.php
src/SymfonyBundle.php
tests/SymfonyBundleTest.php

Fix auto-detection of bundles

---

src/Flex.php
src/Recipe.php

Fix BC break

---

src/SymfonyBundle.php
tests/SymfonyBundleTest.php

Fix bundle detection when PSR-4 autoloading using several directories

---

src/Configurator/EnvConfigurator.php

See https://github.com/symfony/recipes/issues/270

do not try to copy .env.dist if it doesn't exist

---

src/Lock.php

Not sure if You guys would like that.
This issue is most visible when removing and adding bundles at the same time. Happened to me when working on https://github.com/symfony/demo/pull/717.

[Proposal] Sorts symfony.lock entries.

---

src/Command/RequireCommand.php
src/PackageResolver.php

Works around https://github.com/composer/composer/issues/6869

Stick to framework-bundle's version by default

---

src/Configurator/EnvConfigurator.php
tests/Configurator/EnvConfiguratorTest.php

Fix commented env vars support

---

src/Flex.php
tests/FlexTest.php

See #238.
I talked with @nicolas-grekas about this. By merging the Flex recipe into FWBundle, we created a possibility (which I hit while creating our upgrade tutorial) that the `.env.dist` file is not present. And then, recipes may start installing incorrectly because this file is needed (so that recipes can update it and `.env`).
The fix is this PR + to revert https://github.com/symfony/recipes/pull/295

Guaranteeing that Flex is installed THEN fwbundle

---

src/Configurator/ContainerConfigurator.php
tests/Configurator/ContainerConfiguratorTest.php

Make ContainerConfigurator use config-dir option for file paths

---

src/Flex.php

needed to merge symfony/skeleton#48

Change license to proprietary when installing a new project from a skeleton

---

src/Configurator/CopyFromRecipeConfigurator.php

This is an attempt to fix https://github.com/symfony/recipes/issues/324  but I haven't tested it properly yet!

Don't remove the main Git directory

---

src/Flex.php
tests/FlexTest.php

A response to https://twitter.com/fabpot/status/938074790023139329

Help people understand generated files are *theirs*

---

src/Flex.php

alternative to https://github.com/symfony/flex/pull/256
sibling to https://github.com/symfony/thanks/pull/28

invite to install and use Thanks

---

src/Flex.php

my bad, didn't notice this early "return"

Fix display of thanks invite

---

src/ParallelDownloader.php

Fix authentication issue on prefetch

---

src/Downloader.php

By leveraging this hook + https://github.com/composer/composer/pull/6985, I'm able to share one connection+SSL context, reducing round-trip latency (next PR.)

Dispatch PluginEvents::PRE_FILE_DOWNLOAD when calling endpoint

---

src/Downloader.php

Fix calling $rfs->getLastHeaders()

---

src/Flex.php

The previous logic base on the `$search = 3;` counter doesn't work because eg `Application` is found several times in the trace, leading to several run of the same logic.
Getting the `ArgvInput` instance is also easier when looking at trace's arguments.
The remaining are CS changes found by php-cs-fixer.

Fix backtrace-related initialization logic

---

src/Configurator/EnvConfigurator.php

Remove usage of ctype_* functions

---

src/Flex.php
tests/FlexTest.php

"Don't hesitate to" is common but has a bit of a negative vibe.
(Could also just start with "Review".)

Reword post-install comment

---

src/Flex.php

Fix contrib recipes being ignored

---

src/Path.php
tests/PathTest.php

Stopped Path::concatenate prefixing a '/' on Windows paths

---

src/Command/RemoveCommand.php
src/Command/RequireCommand.php
src/Command/UnpackCommand.php
src/Command/UpdateCommand.php
src/Flex.php

Now fixes 3 issues:
- BC with Composer 1.0
- Flex aliases with Composer 1.1
- thanks reminder should need package AND command update
Best reviewed compared to v1.0.63: https://github.com/symfony/flex/compare/v1.0.63...54d6a5dc4a3e6cf9338d46ed51fdf7ea4efef78d

Fix BC with Composer 1.0

---

src/Flex.php

Fix command registration

---

src/Flex.php

Fix https://github.com/symfony/skeleton/issues/55

Fix Composer 1.0 incompatibility

---

src/CurlDownloader.php

Fix https://github.com/symfony/thanks/issues/42

Fix cURL error handling

---

src/Command/UnpackCommand.php

Get the right version when unpacking instead of a random one. Fixes #315

Fixed unpacking packages

---

src/Flex.php
src/Recipe.php

Add the link to contrib recipes when asking the user to confirm installation

---

src/Flex.php

Fix wrong content hash in composer.lock

---

src/Flex.php

Allow customization of the symfony.lock file name

---

src/Configurator/GitignoreConfigurator.php
tests/Configurator/GitignoreConfiguratorTest.php

Expand targer dirs in .gitignore

---

src/Flex.php
src/ParallelDownloader.php

Honor --no-progress

---

src/Command/InstallRecipesCommand.php
src/Flex.php

Add a new command to install missing recipes

---

src/Command/FixRecipesCommand.php
src/Flex.php

Rename intall-recipes to fix-recipes

---

tests/Configurator/CopyDirectoryFromPackageConfiguratorTest.php

This PR
💁‍♂️ Should https://fabbot.io be enabled for this repository?

Fix: Run php-cs-fixer

---

src/Downloader.php

Fix: Remove unused property

---

src/Command/FixRecipesCommand.php
src/Command/RequireCommand.php
src/Command/UnpackCommand.php

Fix: Case mismatch

---

src/Command/FixRecipesCommand.php

Remove private class

---

src/Flex.php

Fixes #285, requires Composer v1.7.

Selectively enable "remove-vcs" instead of disabling interactivity

---

src/ComposerRepository.php
src/Flex.php
src/TruncatedComposerRepository.php

Fixes #381
Fixes #382 
Replaces #384

Fix bad wiring of repository manager

---

src/Downloader.php

Fixing duplicate Cache error

---

src/Cache.php
src/TruncatedComposerRepository.php

Fix dealing with bad json bodies

---

src/CurlDownloader.php
src/ScriptExecutor.php

Fixes #400
Fixes https://github.com/composer/composer/issues/7493
I'm not sure why (php or ext-curl bug?), but this change fixes the issue (reproduced locally).

Fix using php://memory on Windows

---

src/ParallelDownloader.php

Fix recursive calls to ParallelDownloader::download()

---

src/Flex.php

Do not configure project if Flex is not explicitly required

---

src/Command/SyncRecipesCommand.php
src/Flex.php

Would make it a bit more obvious what the command is for IMHO.
Related to https://github.com/symfony/flex/pull/439

Rename fix-recipes to sync-recipes

---

composer.json
src/ScriptExecutor.php

per https://github.com/symfony/flex/pull/446/files#r240585349

Use ProcessExecutor::escape()

---

src/ScriptExecutor.php

Fixes #431. Replaces #455 and #453.

Improve error when an invalid auto-script is found

---

src/Command/SyncRecipesCommand.php
src/Flex.php
src/Options.php
tests/Configurator/CopyFromPackageConfiguratorTest.php
tests/Configurator/CopyFromRecipeConfiguratorTest.php

Improve sync-recipes --force

---

composer.json

we made some pretty significant improvements recently, time to bump?

Bump branch alias to 1.2-dev

---

src/SymfonyBundle.php
tests/SymfonyBundleTest.php

Add support for multiple bundles in auto-generated recipes

---

src/Configurator/AbstractConfigurator.php
src/Configurator/EnvConfigurator.php
src/Configurator/GitignoreConfigurator.php
src/Configurator/MakefileConfigurator.php
tests/Configurator/EnvConfiguratorTest.php
tests/Configurator/GitignoreConfiguratorTest.php
tests/Configurator/MakefileConfiguratorTest.php

Fixes #457
This PR is a continuity of https://github.com/symfony/flex/pull/458

Honor --force option in configurators

---

src/SymfonyBundle.php
tests/SymfonyBundleTest.php

They use a special convention: `Bundle` is replaced by `Plugin`.

Add support for Sylius plugins

---

src/Cache.php
tests/CacheTest.php

Further decoupling from symfony/symfony replace section

---

src/Flex.php

This is not needed anymore since https://github.com/composer/composer/pull/7454 and Composer 1.7.3 and nobody told us? /cc @stof :)

Don't preload packages listed in "conflict" nor "replace"

---

src/Flex.php

Fix rebooting composer on install

---

src/Cache.php
src/Flex.php
src/TruncatedComposerRepository.php
tests/CacheTest.php

Solves https://github.com/symfony/flex/issues/527

Defer fetching the versions.json until it is needed

---

src/Configurator/ContainerConfigurator.php
src/Downloader.php
src/Flex.php
tests/Configurator/ContainerConfiguratorTest.php

Fix var_export on ContainerConfigurator

Fix var_export on ContainerConfigurator

---

src/Flex.php

Disable recipes when run from global

---

src/Unpacker.php

Fix unpacking when private packagist is used

---

src/Flex.php

Instead of creating a separate set of "composer" and "installer" objects, this PR recycles them so that plugins run in the same scope.
Fix #529

Fix running other plugins on create-project

---

src/Flex.php

Check if autoload.php exists before trying to update it

---

src/Command/SyncRecipesCommand.php

Hi! 
Very simple: you can now re-install/update just one (or specific) recipes:
```
composer symfony:sync-recipes symfony/console --force
```
That's very helpful, as there are a few specific recipes (this is one of them) that really *do* need to be "updated", at the very least, when upgrading to Symfony 5 (as some important files have evolved over time).
This relates to #575 (will help with upgrading), #518 and should go along with the PRs #562 and #565
Thanks!

Allowing specific recipes to be "re-installed"

---

src/Command/SyncRecipesCommand.php
src/Configurator/CopyFromPackageConfigurator.php
src/Configurator/CopyFromRecipeConfigurator.php
src/Configurator/EnvConfigurator.php
src/Configurator/GitignoreConfigurator.php
src/Configurator/MakefileConfigurator.php

Slightly nicer output (the indentation):
Super minor - sorry for extra noise :)

Notifying of -v option and making output better for recipe info

---

tests/Configurator/CopyFromPackageConfiguratorTest.php
tests/Configurator/CopyFromRecipeConfiguratorTest.php

Since #584, the tests have failed

Fix travis test

---

src/Command/InstallRecipesCommand.php
src/Flex.php

Step 2 of #518, `symfony:recipes:install` command

Rename SyncRecipes on InstallRecipes

---

src/Command/RecipesCommand.php

This allows us to always show the history - even if the version changed

showing commit history for entire recipe - not just specific version

---

src/Flex.php

As reported by @stof in https://github.com/symfony/flex/pull/576#discussion_r357552402

Update autoload.php on POST_AUTOLOAD_DUMP

---

src/Command/DumpEnvCommand.php

Sidekick of https://github.com/symfony/symfony/pull/35308

Add forward compat with Dotenv v5.1

---

src/Command/UpdateCommand.php

Set --no-suggest option to true only on Composer 1

---

src/Flex.php

@nicolas-grekas I should fix #636 when flex is installed globally

Fix compatibility downloader on global install

---

src/Cache.php
src/PackageFilter.php

Handle branch alias in filtered packages

---

src/Unpacker.php

When a pack refers e.g. `doctrine/orm: *`, this will unpack it as `doctrine/orm: ^2.7`.
(note that this won't apply to Symfony components, which are already unpacked according to the `extra.symfony.require` rule)

Lock the major-version when unpacking unbounded constraints

---

src/Command/RequireCommand.php

Running `composer req --unpack api-admin` doesn't install [the recipe for api-platform/admin-pack](https://github.com/symfony/recipes/tree/master/api-platform/admin-pack/1.0).
This fixes it.

Fix composer require --unpack not installing recipes for the packs

---

src/Command/RequireCommand.php
src/Command/UnpackCommand.php
src/Unpacker.php

Fix unpacking

---

src/Unpacker.php

https://github.com/composer/composer/blob/2.0.0-alpha2/src/Composer/Package/Locker.php#L78
https://github.com/composer/composer/blob/1.10.8/src/Composer/Package/Locker.php#L73
`Locker::getContentHash` is static method.

use static construction for static method

---

tests/PathTest.php

I wanted to make sure I understand how concatenate on Path works for my
PR for #513 and maybe the tests are valuable to others as well.

Adds tests for Path helper.

---

src/ParallelDownloader.php

Fix compat with composer v2

---

src/Unpacker.php

Fix unpacking nested packs into composer.json

---

src/Flex.php
src/Unpacker.php
tests/FlexTest.php
tests/UnpackerTest.php

Fix Unpacker failing on Intervals::compactConstraint()

---

src/Unpacker.php

Fix Unpacker

---

src/InformationOperation.php

See https://github.com/composer/composer/commit/09ef026d43fc5ac032d083241e2cab0320ddd325

Fix InformationOperation breaking on latest Composer 2.x

---

src/Unpacker.php

Fixes #684 
`Intervals::compactConstraint()` doesn't do what we thought it did.

Dont compact constraints on Composer 2

---

src/PackageFilter.php

This also fixes support for branch `5.x`

Fix support for ".x" branches

---

src/Flex.php
src/PackageFilter.php
tests/CacheTest.php
tests/FlexTest.php
tests/PackageFilterTest.php

As hinted in https://github.com/composer/composer/issues/9290#issuecomment-708965515

Don't filter locked packages

---

tests/FlexTest.php

Removed duplicated array key.
_Previous PR #698 was closed automatically after changing the default branch from master to main._

Removed duplicated array key

---

src/Command/RecipesCommand.php

New flag to list only outdated recipes

---

src/Cache.php
src/Flex.php
src/PackageFilter.php
src/TruncatedComposerRepository.php
tests/CacheTest.php
tests/PackageFilterTest.php

Fixes https://github.com/symfony/flex/issues/712
Fixes https://github.com/composer/composer/issues/9409
Fixes https://twitter.com/scherzmut/status/1323609763125612546

Use root constraints when they have no intersection with extra.symfony.require

---

composer.json
src/Flex.php
src/PackageJsonSynchronizer.php
tests/Fixtures/packageJson/assets/controllers.json
tests/Fixtures/packageJson/package.json
tests/Fixtures/packageJson/vendor/symfony/existing-package/Resources/assets/package.json
tests/Fixtures/packageJson/vendor/symfony/new-package/assets/package.json
tests/PackageJsonSynchronizerTest.php

Implement package.json synchronization for Symfony UX

Implement package.json synchronization

---

src/Configurator/DockerComposeConfigurator.php
tests/Configurator/DockerComposeConfiguratorTest.php

This PR implements the rules described in the Docker Compose manual: https://docs.docker.com/compose/reference/envvars/#compose_file (see also https://github.com/symfony/flex/pull/705#issuecomment-722569904, cc @jycamier).
Basically, the directory containing the Compose definition can be configured using the `COMPOSE_FILE` environment variable, and it isn't defined Flex will look for the Compose file (as `docker-compose itself`) in the project directory and then in each parent director. 
This will be especially helpful for API Platform, where the `docker-compose.yml` file is in the parent directory of the Symfony application (https://github.com/api-platform/api-platform/), but also for other monolithic Git repositories containing several applications and a `docker-compose.yaml` file at …

Improve Docker Compose file detection

---

src/Command/DumpEnvCommand.php
tests/Command/DumpEnvCommandTest.php

Make "env" argument in symfony:dump-env optional

---

src/PackageJsonSynchronizer.php
tests/PackageJsonSynchronizerTest.php

fix package sorting

---

src/Command/DumpEnvCommand.php

Fixes #741
Let's wait for confirmation by @Seldaek before merging.

Require autoload.php in dump-env

---

src/Flex.php
src/PackageJsonSynchronizer.php

Don't warn about npm/yarn unless there is a ux-package in vendor/

---

src/PackageJsonSynchronizer.php
tests/Fixtures/packageJson/vendor/symfony/existing-package/Resources/assets/package.json
tests/Fixtures/packageJson/vendor/symfony/new-package/assets/package.json
tests/PackageJsonSynchronizerTest.php

As spotted in https://github.com/symfony/ux/pull/93
/cc @weaverryan

Copy peerDependencies to the root package.json

---

src/Flex.php
src/PackageJsonSynchronizer.php
tests/FlexTest.php
tests/PackageJsonSynchronizerTest.php

Use Composer vendor-dir

---

src/Command/GenerateIdCommand.php
src/Flex.php
src/InformationOperation.php
src/PackageJsonSynchronizer.php
tests/Fixtures/packageJson/vendor/symfony/existing-package/composer.json
tests/Fixtures/packageJson/vendor/symfony/new-package/composer.json
tests/PackageJsonSynchronizerTest.php

Fix looking for keywords

---

src/Flex.php
src/PackageJsonSynchronizer.php

Support for smooth upgrades from older flex versions

---

src/Command/UnpackCommand.php
src/Configurator/CopyFromPackageConfigurator.php
src/Flex.php
src/Unpacker.php

Unpack entries from require-dev

---

src/Command/RequireCommand.php
src/Command/UnpackCommand.php
src/Flex.php

Deprecate not-unpacking, fix unpacking

---

src/Flex.php
tests/FlexTest.php

See symfony/recipes#991 for some screenshots.

Add a better output for post install instructions

---

src/Flex.php
tests/FlexTest.php

Skip doing anything on "install"

---

src/Flex.php

Fixes #775
Removed code that was implemented in #576 as this is no longer needed as per the issue reported.
First PR in this repository. Hoping to contribute to more! If there are any issues, let me know.

removed unnecessary code

---

src/Command/RecipesCommand.php

Dont fail displaying info about not installed recipes

---

src/PackageJsonSynchronizer.php

Look into vendor's src/Resources/assets for package.json

---

src/Downloader.php

Fix compat with older composer

---

src/Downloader.php

Fix handling flex://defaults

---

src/Downloader.php

Use default endpoints as fallbacks if Composer endpoint is specified as string
